spring:
  # 数据源
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/site?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none    # 根据实体类更新表结构
    show-sql: true        # 输出SQL语句

logging:
  level:
    root: warning
    com.scy.mysite: info

server:
  port: 521
